In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(type(a[0]))

<class 'numpy.int64'>


In [5]:
a.shape

(4,)

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [10]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [16]:
X = np.random.randint(0,2,10)
#O to 2 - Range, 10 Numbers in array

In [17]:
X 

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [18]:
Y = np.random.randint(0,10,(5,5))

In [19]:
Y

array([[5, 5, 2, 2, 5],
       [2, 5, 8, 6, 3],
       [7, 0, 7, 8, 8],
       [7, 0, 8, 0, 0],
       [4, 4, 4, 6, 0]])

In [20]:
np.min(Y)

0

In [21]:
np.argmin(Y)

11

In [22]:
np.unique(Y)

array([0, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.unique(Y,return_counts=True)

(array([0, 2, 3, 4, 5, 6, 7, 8]), array([5, 3, 1, 3, 4, 2, 3, 4]))